server:
  port: 8083
spring:
  application:
    name: "weather-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  rabbitmq:
    host: localhost
    password: guest
    username: guest
    virtual_host: /
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 0
process:
  concurrency: "1-1"
