server:
  port: 8083
spring:
  application:
    name: "weather-processing"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri:  ${MONGO_URL}
azure:
  connection-string: ${SB_URL}
